version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-3000}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src

  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./app:/app
    working_dir: /app
    command: "npm run dev"
    depends_on:
      - api
