version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-3000}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
